app_home:
  path: /
  controller: App\Controller\HomeController::index

register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_forgot_password_request:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request

app_check_email:
  path: /reset-password/check-email
  controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
  path: /reset-password/reset/{token}
  controller: App\Controller\ResetPasswordController::reset
